[package]
name = "echo_wallet_config"
version = "5.4.0-alpha.1"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
description = "Configuration for grin wallet , a simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/echo-wallet"
keywords = [ "crypto", "grin", "mimblewimble" ]
workspace = ".."
edition = "2018"

[dependencies]
rand = "0.6"
serde = "1"
serde_derive = "1"
toml = "0.5"
dirs = "2.0"

echo_wallet_util = { path = "../util", version = "5.4.0-alpha.1" }

##### Grin Imports

# For Release
# echo_core = "5.3.3"
# echo_util = "5.3.3"

# For beta release

#echo_core = { git = "https://github.com/mimblewimble/grin", tag = "v5.2.0-beta.3"}
#echo_util = { git = "https://github.com/mimblewimble/grin", tag = "v5.2.0-beta.3" }

# For bleeding edge
# echo_core = { git = "https://github.com/mimblewimble/grin", branch = "master" }
# echo_util = { git = "https://github.com/mimblewimble/grin", branch = "master" }

# For local testing
echo_core = { path = "../../echo/core"}
echo_util = { path = "../../echo/util"}

#####

[dev-dependencies]
pretty_assertions = "0.6"

